name: CR

on:
  push:
    branches:
      - main

jobs:        
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release
        id: prepare
        uses: karlhulme/github-action-prepare-release@master
        with:
          branchName: main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create GitHub Release
        if: steps.prepare.outputs.canRelease == 'yes'
        id: release
        uses: karlhulme/github-action-create-release@master
        with:
          branchName: main
          releaseVersion: ${{ steps.prepare.outputs.releaseVersion }}
          releaseNotes: ${{ steps.prepare.outputs.releaseNotes }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Clone repo
        if: steps.prepare.outputs.canRelease == 'yes'
        uses: actions/checkout@v1
        with:
          ref: v${{ steps.prepare.outputs.releaseVersion }}

      - name: Setup Node.js 12
        if: steps.prepare.outputs.canRelease == 'yes'
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Publish to NPM
        if: steps.prepare.outputs.canRelease == 'yes'
        run: |
          npm ci
          npm run docker-build
          npm run docker-push
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
